# Generated by Django 5.1.6 on 2025-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, upload_to='profiles/', verbose_name='profile picture'),
        ),
    ]
