# Generated by Django 5.1.6 on 2025-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('transgender', 'Transgender'), ('other', 'Other')], max_length=20, verbose_name='gender'),
        ),
    ]
